# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeinfo',
            old_name='ttile',
            new_name='ttitle',
        ),
    ]
